<?php

// Exit if accessed directly
if( !defined( 'ABSPATH' ) ) {
	exit;
}

/**
 *
 * WARNING: Please do not edit this file in any way
 *
 * load the theme function files
 */

function mytheme_enqueue_scripts() {
// register AngularJS
    wp_register_script('angular-core', 'https://ajax.googleapis.com/ajax/libs/angularjs/1.2.14/angular.js', array(), null, false);

// register our app.js, which has a dependency on angular-core
    wp_register_script('angular-app', get_bloginfo('template_directory').'/app.js', array('angular-core'), null, false);
//    wp_register_script('maps','http://maps.google.com/maps/api/js?sensor=false', array(), null, false);
//    wp_register_script('loadsh', get_bloginfo('template_directory').'/core/js/loadsh.js', array(), null, false);
//    wp_register_script('angular-google-maps', get_bloginfo('template_directory').'/core/js/angular-google-maps.js', array(), null, false);
//    wp_register_script('stam','http://rawgit.com/allenhwkim/angularjs-google-maps/master/build/scripts/ng-map.min.js', array(), null, false);

// enqueue all scripts
    wp_enqueue_script('angular-core');
    wp_enqueue_script('angular-app');
//    wp_enqueue_script('loadsh');
//    wp_enqueue_script('maps');
//    wp_enqueue_media('angular-google-maps');
//    wp_enqueue_media('stam');

// we need to create a JavaScript variable to store our API endpoint...
    wp_localize_script( 'angular-core', 'AppAPI', array( 'url' => get_bloginfo('wpurl').'/api/') ); // this is the API address of the JSON API plugin
// ... and useful information such as the theme directory and website url
    wp_localize_script( 'angular-core', 'BlogInfo', array( 'url' => get_bloginfo('template_directory').'/', 'site' => get_bloginfo('wpurl')) );
}
add_action('wp_enqueue_scripts', 'mytheme_enqueue_scripts');

$template_directory = get_template_directory();

require( $template_directory . '/core/includes/functions.php' );
require( $template_directory . '/core/includes/functions-update.php' );
require( $template_directory . '/core/includes/functions-rescalls.php' );
require( $template_directory . '/core/includes/functions-install.php' );
require( $template_directory . '/core/includes/theme-options/theme-options.php' );
require( $template_directory . '/core/includes/post-custom-meta.php' );
require( $template_directory . '/core/includes/tha-theme-hooks.php' );
require( $template_directory . '/core/includes/hooks.php' );
require( $template_directory . '/core/includes/version.php' );
require( $template_directory . '/core/includes/upsell/theme-upsell.php' );

// Return value of the supplied responsive free theme option.
function responsive_free_get_option( $option, $default = false ) {
	global $responsive_options;

	// If the option is set then return it's value, otherwise return false.
	if( isset( $responsive_options[$option] ) ) {
		return $responsive_options[$option];
	}

	return $default;
}
